import { AchievementTemplate } from '../types';

export const ACHIEVEMENT_CATALOG: AchievementTemplate[] = [
    // --- WEALTH (Net Worth Milestones) ---
    // HARD MODE: Starting Capital is £1,000,000. 
    // First achievement is DOUBLING your money (£2M).
    { id: 'wealth_1', title: 'Doubled Up', description: 'Reach a Net Worth of £2,000,000', icon: '🌱', category: 'Wealth', condition: { type: 'netWorth', value: 2000000 }, xpReward: 1000, tier: 'bronze', target: 2000000 },
    { id: 'wealth_2', title: 'High Net Worth', description: 'Reach a Net Worth of £5,000,000', icon: '🌿', category: 'Wealth', condition: { type: 'netWorth', value: 5000000 }, xpReward: 2500, tier: 'bronze', target: 5000000 },
    { id: 'wealth_3', title: 'Eight Figures', description: 'Reach a Net Worth of £10,000,000', icon: '💼', category: 'Wealth', condition: { type: 'netWorth', value: 10000000 }, xpReward: 5000, tier: 'silver', target: 10000000 },
    { id: 'wealth_4', title: 'Quarter Century', description: 'Reach a Net Worth of £25,000,000', icon: '🏦', category: 'Wealth', condition: { type: 'netWorth', value: 25000000 }, xpReward: 10000, tier: 'silver', target: 25000000 },
    { id: 'wealth_5', title: 'Half Century', description: 'Reach a Net Worth of £50,000,000', icon: '💰', category: 'Wealth', condition: { type: 'netWorth', value: 50000000 }, xpReward: 25000, tier: 'gold', target: 50000000 },
    { id: 'wealth_6', title: 'Nine Figures', description: 'Reach a Net Worth of £100,000,000', icon: '💎', category: 'Wealth', condition: { type: 'netWorth', value: 100000000 }, xpReward: 50000, tier: 'gold', target: 100000000 },
    { id: 'wealth_7', title: 'Quarter Billion', description: 'Reach a Net Worth of £250,000,000', icon: '🚀', category: 'Wealth', condition: { type: 'netWorth', value: 250000000 }, xpReward: 100000, tier: 'gold', target: 250000000 },
    { id: 'wealth_8', title: 'Half Billion', description: 'Reach a Net Worth of £500,000,000', icon: '🏰', category: 'Wealth', condition: { type: 'netWorth', value: 500000000 }, xpReward: 250000, tier: 'gold', target: 500000000 },
    { id: 'wealth_9', title: 'Billionaire', description: 'Reach a Net Worth of £1,000,000,000', icon: '👑', category: 'Wealth', condition: { type: 'netWorth', value: 1000000000 }, xpReward: 1000000, tier: 'gold', target: 1000000000 },
    { id: 'wealth_10', title: 'Multi-Billionaire', description: 'Reach a Net Worth of £5,000,000,000', icon: '🐋', category: 'Wealth', condition: { type: 'netWorth', value: 5000000000 }, xpReward: 2500000, tier: 'gold', target: 5000000000 },
    { id: 'wealth_11', title: 'Decabillionaire', description: 'Reach a Net Worth of £10,000,000,000', icon: '🌍', category: 'Wealth', condition: { type: 'netWorth', value: 10000000000 }, xpReward: 5000000, tier: 'gold', target: 10000000000 },
    { id: 'wealth_12', title: 'Empire Builder', description: 'Reach a Net Worth of £50,000,000,000', icon: '🌌', category: 'Wealth', condition: { type: 'netWorth', value: 50000000000 }, xpReward: 10000000, tier: 'gold', target: 50000000000 },
    { id: 'wealth_13', title: 'Centibillionaire', description: 'Reach a Net Worth of £100,000,000,000', icon: '🦄', category: 'Wealth', condition: { type: 'netWorth', value: 100000000000 }, xpReward: 25000000, tier: 'gold', target: 100000000000 },
    { id: 'wealth_14', title: 'Trillionaire', description: 'Reach a Net Worth of £1,000,000,000,000', icon: '🪐', category: 'Wealth', condition: { type: 'netWorth', value: 1000000000000 }, xpReward: 100000000, tier: 'gold', target: 1000000000000 },

    // --- PROFIT (Realized Gains) ---
    // Scaled up significantly. Pocket change is now £100k.
    { id: 'profit_1', title: 'Pocket Change', description: 'Make £100,000 total profit', icon: '🪙', category: 'Wealth', condition: { type: 'profit_total', value: 100000 }, xpReward: 500, tier: 'bronze', target: 100000 },
    { id: 'profit_2', title: 'Serious Money', description: 'Make £500,000 total profit', icon: '💵', category: 'Wealth', condition: { type: 'profit_total', value: 500000 }, xpReward: 1000, tier: 'bronze', target: 500000 },
    { id: 'profit_3', title: 'Million Maker', description: 'Make £1,000,000 total profit', icon: '💸', category: 'Wealth', condition: { type: 'profit_total', value: 1000000 }, xpReward: 2500, tier: 'silver', target: 1000000 },
    { id: 'profit_4', title: 'Multi-Million', description: 'Make £5,000,000 total profit', icon: '💰', category: 'Wealth', condition: { type: 'profit_total', value: 5000000 }, xpReward: 10000, tier: 'silver', target: 5000000 },
    { id: 'profit_5', title: 'Eight Figure Profit', description: 'Make £10,000,000 total profit', icon: '🏦', category: 'Wealth', condition: { type: 'profit_total', value: 10000000 }, xpReward: 25000, tier: 'gold', target: 10000000 },
    { id: 'profit_6', title: 'Whale Profit', description: 'Make £50,000,000 total profit', icon: '💎', category: 'Wealth', condition: { type: 'profit_total', value: 50000000 }, xpReward: 100000, tier: 'gold', target: 50000000 },
    { id: 'profit_7', title: 'Nine Figure Profit', description: 'Make £100,000,000 total profit', icon: '🚀', category: 'Wealth', condition: { type: 'profit_total', value: 100000000 }, xpReward: 250000, tier: 'gold', target: 100000000 },

    // --- TRADING (Activity) ---
    { id: 'trade_1', title: 'Rookie', description: 'Complete 10 trades', icon: '👶', category: 'Trading', condition: { type: 'trades', value: 10 }, xpReward: 100, tier: 'bronze', target: 10 },
    { id: 'trade_2', title: 'Trader', description: 'Complete 50 trades', icon: 'wc', category: 'Trading', condition: { type: 'trades', value: 50 }, xpReward: 500, tier: 'bronze', target: 50 },
    { id: 'trade_3', title: 'Active', description: 'Complete 100 trades', icon: '🏃', category: 'Trading', condition: { type: 'trades', value: 100 }, xpReward: 1000, tier: 'silver', target: 100 },
    { id: 'trade_4', title: 'Day Trader', description: 'Complete 500 trades', icon: '⚡', category: 'Trading', condition: { type: 'trades', value: 500 }, xpReward: 5000, tier: 'silver', target: 500 },
    { id: 'trade_5', title: 'Pro', description: 'Complete 1,000 trades', icon: '👔', category: 'Trading', condition: { type: 'trades', value: 1000 }, xpReward: 10000, tier: 'gold', target: 1000 },
    { id: 'trade_6', title: 'Veteran', description: 'Complete 5,000 trades', icon: '🎖️', category: 'Trading', condition: { type: 'trades', value: 5000 }, xpReward: 50000, tier: 'gold', target: 5000 },
    { id: 'trade_7', title: 'Legend', description: 'Complete 10,000 trades', icon: '🏆', category: 'Trading', condition: { type: 'trades', value: 10000 }, xpReward: 100000, tier: 'gold', target: 10000 },

    // --- MASTERY (Skill) ---
    { id: 'mastery_1', title: 'Good Call', description: '>10% gain on a trade', icon: '✅', category: 'Mastery', condition: { type: 'gain_percent', value: 10 }, xpReward: 250, tier: 'bronze', target: 10 },
    { id: 'mastery_2', title: 'Great Call', description: '>25% gain on a trade', icon: '📈', category: 'Mastery', condition: { type: 'gain_percent', value: 25 }, xpReward: 500, tier: 'bronze', target: 25 },
    { id: 'mastery_3', title: 'Moonshot', description: '>50% gain on a trade', icon: '🚀', category: 'Mastery', condition: { type: 'gain_percent', value: 50 }, xpReward: 1000, tier: 'silver', target: 50 },
    { id: 'mastery_4', title: 'Doubler', description: '>100% gain on a trade', icon: '2️⃣', category: 'Mastery', condition: { type: 'gain_percent', value: 100 }, xpReward: 2500, tier: 'gold', target: 100 },
    { id: 'mastery_5', title: 'Multi-Bagger', description: '>500% gain on a trade', icon: '💰', category: 'Mastery', condition: { type: 'gain_percent', value: 500 }, xpReward: 10000, tier: 'gold', target: 500 },
    { id: 'mastery_6', title: '10x', description: '>1000% gain on a trade', icon: '🔟', category: 'Mastery', condition: { type: 'gain_percent', value: 1000 }, xpReward: 25000, tier: 'gold', target: 1000 },
    { id: 'mastery_7', title: 'Consistency', description: '5 profitable trades in a row', icon: '🔥', category: 'Mastery', condition: { type: 'win_streak', value: 5 }, xpReward: 1000, tier: 'silver', target: 5 },
    { id: 'mastery_8', title: 'On Fire', description: '10 profitable trades in a row', icon: '⚡', category: 'Mastery', condition: { type: 'win_streak', value: 10 }, xpReward: 5000, tier: 'gold', target: 10 },
    { id: 'mastery_9', title: 'Unstoppable', description: '20 profitable trades in a row', icon: '🌪️', category: 'Mastery', condition: { type: 'win_streak', value: 20 }, xpReward: 10000, tier: 'gold', target: 20 },
    { id: 'mastery_10', title: 'God Mode', description: '50 profitable trades in a row', icon: '👑', category: 'Mastery', condition: { type: 'win_streak', value: 50 }, xpReward: 50000, tier: 'gold', target: 50 },

    // --- RISK (Volatility) ---
    { id: 'risk_1', title: 'Diversified', description: 'Hold 10 stocks', icon: '📊', category: 'Risk', condition: { type: 'diversity', value: 10 }, xpReward: 500, tier: 'bronze', target: 10 },
    { id: 'risk_2', title: 'Fund Manager', description: 'Hold 25 stocks', icon: '🌐', category: 'Risk', condition: { type: 'diversity', value: 25 }, xpReward: 1000, tier: 'silver', target: 25 },
    { id: 'risk_3', title: 'Concentrated', description: '>50% in 1 stock', icon: '🎯', category: 'Risk', condition: { type: 'concentration', value: 50 }, xpReward: 1000, tier: 'silver', target: 50 },
    { id: 'risk_4', title: 'All In', description: '>90% in 1 stock', icon: '🎲', category: 'Risk', condition: { type: 'concentration', value: 90 }, xpReward: 2500, tier: 'gold', target: 90 },
    { id: 'risk_5', title: 'YOLO', description: '<£100 cash remaining', icon: '🎰', category: 'Risk', condition: { type: 'low_cash', value: 100 }, xpReward: 500, tier: 'bronze', target: 100 },
    { id: 'risk_6', title: 'Whale Trade', description: 'Trade >£1,000,000 value', icon: '🐋', category: 'Risk', condition: { type: 'trade_size', value: 1000000 }, xpReward: 5000, tier: 'gold', target: 1000000 },

    // --- RESILIENCE (Losses) ---
    { id: 'loss_1', title: 'Bad Day', description: 'Lose >10% on a trade', icon: '📉', category: 'Risk', condition: { type: 'loss_percent', value: 10 }, xpReward: 100, tier: 'bronze', target: 10 },
    { id: 'loss_2', title: 'Rekt', description: 'Lose >50% on a trade', icon: '💀', category: 'Risk', condition: { type: 'loss_percent', value: 50 }, xpReward: 1000, tier: 'silver', target: 50 },
    { id: 'loss_3', title: 'Liquidation', description: 'Lose >90% on a trade', icon: '⚰️', category: 'Risk', condition: { type: 'loss_percent', value: 90 }, xpReward: 5000, tier: 'gold', target: 90 },
    { id: 'loss_4', title: 'Heavy Bag', description: 'Total Loss > £100,000', icon: '🎒', category: 'Risk', condition: { type: 'loss_total', value: 100000 }, xpReward: 2500, tier: 'silver', target: 100000 },
    { id: 'loss_5', title: 'Capitulation', description: 'Total Loss > £1,000,000', icon: '🏳️', category: 'Risk', condition: { type: 'loss_total', value: 1000000 }, xpReward: 10000, tier: 'gold', target: 1000000 },

    // --- SECRET (Hidden) ---
    { id: 'secret_1', title: 'Night Owl', description: 'Trade between 2-5 AM', icon: '🦉', category: 'Secret', condition: { type: 'time_trade', value: 1 }, xpReward: 500, tier: 'bronze', target: 1 },
    { id: 'secret_2', title: 'Diamond Hands', description: 'No sells for 30 days', icon: '💎', category: 'Secret', condition: { type: 'no_sell_streak', value: 30 }, xpReward: 5000, tier: 'gold', target: 30 },
    { id: 'secret_3', title: 'Loyal', description: '30 Day Login Streak', icon: '📅', category: 'Secret', condition: { type: 'login_streak', value: 30 }, xpReward: 5000, tier: 'gold', target: 30 },
    { id: 'secret_4', title: 'Addicted', description: '100 Day Login Streak', icon: '💉', category: 'Secret', condition: { type: 'login_streak', value: 100 }, xpReward: 25000, tier: 'gold', target: 100 },

    // --- CULTURE (Meme & Wall Street) ---
    { id: 'cult_1', title: 'Wolf of Wall Street', description: 'Make £1,000,000 profit in one day', icon: '🐺', category: 'Culture', condition: { type: 'profit_day', value: 1000000 }, xpReward: 50000, tier: 'gold', target: 1000000 },
    { id: 'cult_2', title: 'Paper Hands', description: 'Sell at a loss within 5 minutes of buying', icon: '🧻', category: 'Culture', condition: { type: 'panic_sell', value: 1 }, xpReward: 100, tier: 'bronze', target: 1 },
    { id: 'cult_3', title: 'To The Moon', description: 'Hold a crypto that pumps 100%', icon: '🚀', category: 'Culture', condition: { type: 'crypto_pump', value: 100 }, xpReward: 5000, tier: 'silver', target: 100 },
    { id: 'cult_4', title: 'Rug Pulled', description: 'Hold a crypto that dumps 90%', icon: '📉', category: 'Culture', condition: { type: 'crypto_dump', value: 90 }, xpReward: 2500, tier: 'silver', target: 90 },
    { id: 'cult_5', title: 'HODL', description: 'Hold a crypto position for 1 year', icon: '🛡️', category: 'Culture', condition: { type: 'hold_time', value: 365 }, xpReward: 100000, tier: 'gold', target: 365 },
    { id: 'cult_6', title: 'Buy The Dip', description: 'Buy when market is in Markdown', icon: '📉', category: 'Culture', condition: { type: 'buy_dip', value: 1 }, xpReward: 500, tier: 'bronze', target: 1 },
    { id: 'cult_7', title: 'Sell The Top', description: 'Sell when market is in Distribution', icon: '🔝', category: 'Culture', condition: { type: 'sell_top', value: 1 }, xpReward: 1000, tier: 'silver', target: 1 },
    { id: 'cult_8', title: 'YOLO King', description: 'Put 100% of portfolio in one Meme Coin', icon: '🤡', category: 'Culture', condition: { type: 'yolo_meme', value: 1 }, xpReward: 5000, tier: 'gold', target: 1 },
    { id: 'cult_9', title: 'Stonks', description: 'Make profit on a Tech stock', icon: '📈', category: 'Culture', condition: { type: 'profit_tech', value: 1 }, xpReward: 250, tier: 'bronze', target: 1 },
    { id: 'cult_10', title: 'Ok Boomer', description: 'Make profit on a Dividend stock', icon: '👴', category: 'Culture', condition: { type: 'profit_div', value: 1 }, xpReward: 250, tier: 'bronze', target: 1 },
    { id: 'cult_11', title: 'Insider Trading', description: 'Trade immediately after News', icon: '🕵️', category: 'Culture', condition: { type: 'news_trade', value: 1 }, xpReward: 1000, tier: 'silver', target: 1 },
    { id: 'cult_12', title: 'Whale Alert', description: 'Move £10M in a single trade', icon: '🐋', category: 'Culture', condition: { type: 'trade_size', value: 10000000 }, xpReward: 25000, tier: 'gold', target: 10000000 },
    { id: 'cult_13', title: 'Bag Holder', description: 'Hold a losing position for >6 months', icon: '🎒', category: 'Culture', condition: { type: 'bag_hold', value: 180 }, xpReward: 5000, tier: 'silver', target: 180 },
    { id: 'cult_14', title: 'Tendies', description: 'Make enough profit to buy a chicken dinner (£10)', icon: '🍗', category: 'Culture', condition: { type: 'profit_trade', value: 10 }, xpReward: 50, tier: 'bronze', target: 10 },
    { id: 'cult_15', title: 'Lambo', description: 'Withdraw £200,000 (Simulated)', icon: '🏎️', category: 'Culture', condition: { type: 'withdraw', value: 200000 }, xpReward: 5000, tier: 'gold', target: 200000 },
    { id: 'cult_16', title: 'Wen Moon', description: 'Check crypto prices 50 times in a day', icon: '🌕', category: 'Culture', condition: { type: 'check_price', value: 50 }, xpReward: 500, tier: 'bronze', target: 50 },
    { id: 'cult_17', title: 'NGMI', description: 'Lose 50% of portfolio value', icon: '☠️', category: 'Culture', condition: { type: 'portfolio_loss', value: 50 }, xpReward: 1000, tier: 'silver', target: 50 },
    { id: 'cult_18', title: 'WAGMI', description: 'Recover from a 50% loss to break even', icon: '🤝', category: 'Culture', condition: { type: 'recovery', value: 1 }, xpReward: 10000, tier: 'gold', target: 1 },
    { id: 'cult_19', title: 'Money Printer', description: 'Receive dividends 10 times', icon: '🖨️', category: 'Culture', condition: { type: 'dividends', value: 10 }, xpReward: 1000, tier: 'silver', target: 10 },
    { id: 'cult_20', title: 'Infinite Brrr', description: 'Receive dividends 100 times', icon: '💵', category: 'Culture', condition: { type: 'dividends', value: 100 }, xpReward: 10000, tier: 'gold', target: 100 },
    { id: 'cult_21', title: 'Buy High Sell Low', description: 'Lose money on 5 consecutive trades', icon: '🧠', category: 'Culture', condition: { type: 'loss_streak', value: 5 }, xpReward: 500, tier: 'bronze', target: 5 },
    { id: 'cult_22', title: 'Technical Analyst', description: 'Use 5 different indicators', icon: '📐', category: 'Culture', condition: { type: 'use_indicators', value: 5 }, xpReward: 500, tier: 'bronze', target: 5 },
    { id: 'cult_23', title: 'Fundamentalist', description: 'Read 50 news articles', icon: '📰', category: 'Culture', condition: { type: 'read_news', value: 50 }, xpReward: 1000, tier: 'silver', target: 50 },
    { id: 'cult_24', title: 'Day Trader', description: 'Open and close a position same day', icon: '☀️', category: 'Culture', condition: { type: 'day_trade', value: 1 }, xpReward: 100, tier: 'bronze', target: 1 },
    { id: 'cult_25', title: 'Swing Trader', description: 'Hold a position for >3 days', icon: '🌊', category: 'Culture', condition: { type: 'swing_trade', value: 1 }, xpReward: 250, tier: 'bronze', target: 1 },
    { id: 'cult_26', title: 'Investor', description: 'Hold a position for >1 month', icon: '🕰️', category: 'Culture', condition: { type: 'investor', value: 1 }, xpReward: 1000, tier: 'silver', target: 1 },
    { id: 'cult_27', title: 'Speculator', description: 'Buy a stock with P/E > 100', icon: '🔮', category: 'Culture', condition: { type: 'high_pe', value: 1 }, xpReward: 500, tier: 'bronze', target: 1 },
    { id: 'cult_28', title: 'Value Hunter', description: 'Buy a stock with P/E < 10', icon: '🔍', category: 'Culture', condition: { type: 'low_pe', value: 1 }, xpReward: 500, tier: 'bronze', target: 1 },
    { id: 'cult_29', title: 'Dividend King', description: 'Earn £10,000 in dividends', icon: '👑', category: 'Culture', condition: { type: 'dividend_val', value: 10000 }, xpReward: 5000, tier: 'gold', target: 10000 },
    { id: 'cult_30', title: 'Tax Loss Harvesting', description: 'Sell a loss at year end (Dec)', icon: '🧾', category: 'Culture', condition: { type: 'tax_loss', value: 1 }, xpReward: 1000, tier: 'silver', target: 1 },
    { id: 'cult_31', title: 'Market Maker', description: 'Have 10 limit orders filled', icon: '🏗️', category: 'Culture', condition: { type: 'limit_fill', value: 10 }, xpReward: 2500, tier: 'silver', target: 10 },
    { id: 'cult_32', title: 'Arbitrage', description: 'Profit from price difference', icon: '⚖️', category: 'Culture', condition: { type: 'arbitrage', value: 1 }, xpReward: 5000, tier: 'gold', target: 1 },
    { id: 'cult_33', title: 'Short Squeeze', description: 'Profit from a short squeeze event', icon: '🍋', category: 'Culture', condition: { type: 'squeeze', value: 1 }, xpReward: 10000, tier: 'gold', target: 1 },
    { id: 'cult_34', title: 'Flash Crash', description: 'Survive a 10% market drop in 1 day', icon: '⚡', category: 'Culture', condition: { type: 'flash_crash', value: 1 }, xpReward: 5000, tier: 'gold', target: 1 },
    { id: 'cult_35', title: 'Dead Cat Bounce', description: 'Profit on a bounce after a crash', icon: '🐱', category: 'Culture', condition: { type: 'bounce', value: 1 }, xpReward: 2500, tier: 'silver', target: 1 },
    { id: 'cult_36', title: 'Falling Knife', description: 'Buy a stock dropping >5% in a day', icon: '🔪', category: 'Culture', condition: { type: 'falling_knife', value: 1 }, xpReward: 1000, tier: 'silver', target: 1 },
    { id: 'cult_37', title: 'FOMO', description: 'Buy a stock at All Time High', icon: '😱', category: 'Culture', condition: { type: 'buy_ath', value: 1 }, xpReward: 500, tier: 'bronze', target: 1 },
    { id: 'cult_38', title: 'FUD Fighter', description: 'Buy during "Extreme Fear"', icon: '🛡️', category: 'Culture', condition: { type: 'buy_fear', value: 1 }, xpReward: 2500, tier: 'gold', target: 1 },
    { id: 'cult_39', title: 'Greed is Good', description: 'Sell during "Extreme Greed"', icon: '😈', category: 'Culture', condition: { type: 'sell_greed', value: 1 }, xpReward: 2500, tier: 'gold', target: 1 },
    { id: 'cult_40', title: 'Contrarian', description: 'Trade against the majority sentiment', icon: '↔️', category: 'Culture', condition: { type: 'contrarian', value: 1 }, xpReward: 5000, tier: 'gold', target: 1 },
    { id: 'cult_41', title: 'Early Adopter', description: 'Buy a new IPO stock', icon: '👶', category: 'Culture', condition: { type: 'ipo', value: 1 }, xpReward: 1000, tier: 'silver', target: 1 },
    { id: 'cult_42', title: 'Blue Chip', description: 'Hold only Top 10 stocks', icon: '🔵', category: 'Culture', condition: { type: 'blue_chip', value: 1 }, xpReward: 1000, tier: 'silver', target: 1 },
    { id: 'cult_43', title: 'Penny Stock', description: 'Trade a stock under £5', icon: '🪙', category: 'Culture', condition: { type: 'penny', value: 1 }, xpReward: 500, tier: 'bronze', target: 1 },
    { id: 'cult_44', title: 'Margin Call', description: 'Reach 0 cash with open positions', icon: '📞', category: 'Culture', condition: { type: 'margin_call', value: 1 }, xpReward: 1000, tier: 'silver', target: 1 },
    { id: 'cult_45', title: 'Liquid', description: 'Hold >50% cash during a crash', icon: '💧', category: 'Culture', condition: { type: 'liquid', value: 1 }, xpReward: 2500, tier: 'gold', target: 1 },
    { id: 'cult_46', title: 'Diversification', description: 'Hold stocks in every sector', icon: '🌈', category: 'Culture', condition: { type: 'all_sectors', value: 1 }, xpReward: 5000, tier: 'gold', target: 1 },
    { id: 'cult_47', title: 'Sector Rotation', description: 'Sell Tech, Buy Energy same day', icon: '🔄', category: 'Culture', condition: { type: 'rotation', value: 1 }, xpReward: 2500, tier: 'silver', target: 1 },
    { id: 'cult_48', title: 'Dollar Cost Average', description: 'Buy same stock 5 times over 5 weeks', icon: '📅', category: 'Culture', condition: { type: 'dca', value: 1 }, xpReward: 5000, tier: 'gold', target: 1 },
    { id: 'cult_49', title: 'Lump Sum', description: 'Invest £100k in one go', icon: '💰', category: 'Culture', condition: { type: 'lump_sum', value: 1 }, xpReward: 2500, tier: 'silver', target: 1 },
    { id: 'cult_50', title: 'The 1%', description: 'Reach Top 1% on Leaderboard', icon: '🏆', category: 'Culture', condition: { type: 'top_1_percent', value: 1 }, xpReward: 100000, tier: 'gold', target: 1 },

];
